<li class="news_list_item">
                    <a href="[field:arcurl/]">
                        <div class="news_item_top clearfix">
                            <h2 class="title left">[field:title/]</h2>
                            <span class="time right">08-23</span>
                        </div>
                        <div class="news_item_bot">
                            <p class="dec">[field:description function="cn_substr(@me,60)"/]...</p>
                            <span class="arrow"><i class="fa fa-long-arrow-right"></i></span>
                        </div>
                    </a>
                </li>