<li><a href="[field:arcurl/]">
                        <div class="pro_item">
                            <div class="pro_item_pic">
                                <img src="[field:picname/]" alt="">
                            </div>
                            <div class="pro_item_dec">
                                <p class="pro_dec_text">[field:title/]</p>
                                <p class="pro_dec_num">00 <span class="line"></span></p>
                                <span class="go_icon"></span>
                            </div>
                        </div>
                    </a></li>