
                        <li class="about_list_item wow zoomIn">
                            <a href="[field:typelink/]">
                                <div class="about_list_pic">
                                    <div class="about_list_pic_in">
                                        <img src="/templets/shengtainongye/static/picture/list[field:id/].png" alt="">
                                    </div>
                                </div>
                                <p class="about_list_name">[field:typename/]</p>
                            </a>
                        </li>
                        