<a href="[field:arcurl/]">
                <p class="news_show_time">[field:pubdate function="GetDateTimeMK(@me)" /]</p>
                <h2 class="news_show_title">[field:title/]</h2>
                <p class="news_show_dec">[field:description function="cn_substr(@me,80)"/]...</p>
                <div class="news_show_pic">
                    <img src="[field:picname/]" alt="">
                </div>
            </a>