<li class="news_con_item wow fadeInUp" data-wow-delay="0.3s">
                        <a href="[field:arcurl/]" class="clearfix">
                            <div class="news_pic left">
                                <img src="[field:picname/]" alt="">
                            </div>
                            <div class="news_info right">
                                <div class="news_time">
                                    <span class="day">26</span>
                                    <p class="year">[field:pubdate function="MyDate('Y-m-d',@me)"/]</p>
                                </div>
                                <div class="news_text">
                                    <h2 class="news_text_tit">[field:title/]</h2>
                                    <p class="news_text_dec">[field:description function="cn_substr(@me,80)"/]...</p>
                                </div>
                            </div>
                        </a>
                    </li>